### ISSUE TITLE
missing how to use description

### ISSUE THREAD

**Issue by DemonGaming420** [budak7273/MovePlayerInventory#1]
please add in the description how to use this mod

**Comment by budak7273** [comment]
The first time you open your inventory in-game, a tutorial will appear that tells you how to use the mod. It's a flashing yellow icon that doesn't go away until you interact with it.

Regardless, I have added the text from the tutorial to the mod page, as well as some extra info.

EDIT: See 016fcb49ed5051529e8f3d7ce88d68516a2f6dfd
